languageCode = "en-us"
title = "Computer Vision Summer Research Program"
subtitle = ""
theme = "simple-blog"
baseURL = "https://ece-courses.github.io/ece-500-site/"
copyright = "© 2020 Leila Abdelrahman -- "
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"

[menu]

  [[menu.main]]
    identifier = "staff"
    name = "Program Coordinators"
    url = "/staff/"
    weight = 5

  [[menu.main]]
    identifier = "office hours"
    name = "Office Hours"
    url = "/office-hours/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Developing and Executing Research Projects"
